let names: string[] = ['Trula', 'Heinrik', 'Herbie', 'Risa', 'Bridgette', 'Jerrome', 'Athene', 'Shandie', 'Dannel', 'Doreen', 'Mohandas', 'Morlee', 
    'Jackson', 'Ced', 'Merry', 'Sebastiano', 'Brendis', 'Quentin', 'Dag', 'Quintin', 'Alaine', 'Auberta', 'Rochella', 'Erskine', 'Clemmie', 'Normie', 
    'Aleen', 'Verile', 'Neal', 'Tod', 'Dawn', 'Artair', 'Elora', 'Wait', 'Vincent', 'Derward', 'Jobina', 'Prinz', 'Helena', 'Irving',
'Hobey', 'Jerald', 'Meris', 'Meggie', 'Mamie', 'Sumner', 'Roscoe', 'Leonardo', 'Inigo', 'Addia', 'Hilarius', 'Gaylor', 'Elonore',
'Glad', 'Gunilla', 'Davide', 'Lek', 'Coralie', 'Abba', 'Mandel', 'Caleb',
'Mallissa', 'Marya', 'Elora', 'Charil', 'Griswold', 'Ewan', 'Joseito', 'Cristobal',
'Sonia', 'Lishe','Hillel', 'Arluene', 'Rodolphe', 'Benoit', 'Taylor', 'Jamima',
'Eugen', 'Chrisy', 'Mal', 'Brynn', 'Nedi', 'Herby', 'Sully', 'Peyter',
'Nona', 'Izak', 'Eric','Pepillo', 'Horton', 'Salvatore', 'Thalia', 'Myrah',
'Gaspard', 'Raynor', 'Danit', 'Donny', 'Dusty', 'Orlando', 'Rhianna', 'Don',
'Lauraine', 'Antonino', 'Herculie', 'Shela', 'Lamond', 'Buddie', 'Burton', 'Daria',
'Paloma', 'Ferne', 'Darsie', 'Waverley', 'Kristan', 'Dolf', 'Pammie', 'Coriss',
'Iona', 'Clay', 'Errick', 'Thacher', 'Cybil', 'Isidro', 'Tades', 'Hardy', 'Tull', 'Alisha'];

let last_names: string[] = ['Bosden', 'Robyns', 'Gilbanks', 'Singyard', 'Janik', 'Gitsham', 'Magowan', 'McAvinchey',
'Rylance', 'Lossman', 'Allbut', 'Flaubert', 'Glossop', 'Kalberer', 'Goldis', 'Bellison',
'Di Baudi', 'Windridge', 'Geist', 'Toomey', 'Grasha', 'Elsmere', 'Preshous', 'Duffin',
'Crossland', 'Eccleshall', 'De Caville', 'Massei', 'Mawford', 'Crowthe', 'Ungerer', 'Paulton',
'Favell', 'Bullerwell', 'Flower', 'Marc', 'Beaty', 'Skeath', 'Giriardelli', 'Riddel',
'McCrohon', 'Calverley', 'Huyton', 'Ivushkin', 'Larmouth', 'Pinkard', 'Hebborn', 'Lingard',
'Munnion', 'Cochrane', 'Pellingar', 'Huot', 'Sasser', 'Havick', 'Ladbrooke', 'Dunnion',
'Oager', 'Padmore', 'Houdhury', 'Hindrick', 'Crippes', 'Tulip', 'MacCrachen', 'Chalcot',
'Pendrich', 'Hurne', 'Titchmarsh', 'Timmermann', 'Flood', 'Blueman', 'Fitzsimon', 'Basil',
'Smolan', 'Wannan', 'Storres', 'Pleace', 'Jezard', 'Easterling', 'Cowx', 'Paumier',
'Hosier', 'Hanrahan', 'Gulk', 'Wagenen', 'Dochon', 'Hillen', 'Doddemeede', 'Hoyles',
'Gorvette', 'McAvey', 'Garfitt', 'Doche', 'Soan', 'Kittle', 'Tolotti', 'Rein',
'Semeniuk', 'Waistall', 'Tolhurst', 'Aisman', 'Hatherleigh', 'Epperson', 'Fassman', 'Spreull',
'Wall', 'Blissitt', 'Kusick', 'Launchbury', 'Cadding', 'Coulthard', 'Chapelle', 'MacNair',
'Skelding', 'Petrakov', 'Pickard', 'Conws', 'Search', 'Brotherton', 'Trayte', 'Streetfield',
'Drohane', 'Lesurf', 'Izakovitz', 'Best', 'Mainson', 'Slocombe', 'Ortiger', 'Skipperbottom',
'Lomath', 'Humberstone', 'Ashford', 'Markwell', 'Pauling', 'Syddie', 'Vell', 'Branni',
'Mealing', 'Ruhben', 'Bolletti', 'Kraft', 'Houltham', 'Grinnov', 'McIlveen', 'Newnham',
'Colmore', 'Marushak', 'Toulmin', 'Kovalski', 'Saurat', 'Cariss', 'Pessler', 'Bortolini',
'Parlatt', 'Bonallick', 'Marquet', 'Eustis', 'Digweed']

module.exports = {names, last_names}